services:
  client:
    image: node:18-alpine
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - VITE_API_URL=http://localhost:3000
    command: >
      sh -c "cd /app &&
             npm install -g pnpm &&
             pnpm install &&
             cd /app/shared &&
             pnpm install &&
             pnpm build &&
             cd /app/client &&
             pnpm install &&
             pnpm dev"
    depends_on:
      - server

  server:
    image: node:18-alpine
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - game_data:/data/games
    env_file:
      - .env
    command: >
      sh -c "cd /app &&
             npm install -g pnpm &&
             pnpm install &&
             cd /app/shared &&
             pnpm install &&
             pnpm build &&
             cd /app/server &&
             pnpm install &&
             pnpm dev"
    depends_on:
      - redis
      - mongodb

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mongodb:
    image: mongo:6-jammy
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  redis_data:
  mongodb_data:
  game_data:
