version: '3.8'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.simple
    volumes:
      - .:/app
      - /app/node_modules
      - /app/shared/node_modules
      - /app/server/node_modules
      - /app/client/node_modules
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      - NODE_ENV=development