
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      server:
        condition: service_healthy
      client:
        condition: service_started

  client:
    image: ${CLIENT_TAG:-ctorgame-client:latest}
    build:
      context: .
      dockerfile: Dockerfile.client
    env_file:
      - .env
    volumes:
      - client_dist:/app/dist

  server:
    image: ${SERVER_TAG:-ctorgame-server:latest}
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - game_data:/data/games
    depends_on:
      - redis
      - mongodb
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mongodb:
    image: mongo:6-jammy
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  redis_data:
  mongodb_data:
  client_dist:
  game_data:
