services:
  client:
    image: node:18-alpine
    working_dir: /app
    init: true
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - pnpm_store:/root/.local/share/pnpm/store/v3
      - client_modules:/app/client/node_modules
      - shared_modules:/app/shared/node_modules
    env_file:
      - .env
    environment:
      - VITE_API_URL=http://localhost:3000
    command: >
      sh -c "cd /app &&
             mkdir -p /app/client/node_modules /app/shared/node_modules &&
             chown -R node:node . &&
             npm install -g pnpm@latest &&
             su node -c 'cd /app && 
             pnpm install --no-workspace-root --frozen-lockfile &&
             cd /app/shared &&
             pnpm install --frozen-lockfile &&
             pnpm build &&
             cd /app/client &&
             pnpm install --frozen-lockfile &&
             pnpm dev'"
    depends_on:
      - server

  server:
    image: node:18-alpine
    working_dir: /app
    init: true
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - game_data:/data/games
      - pnpm_store:/root/.local/share/pnpm/store/v3
      - server_modules:/app/server/node_modules
      - shared_modules:/app/shared/node_modules
    env_file:
      - .env
    command: >
      sh -c "cd /app &&
             mkdir -p /app/server/node_modules /app/shared/node_modules &&
             chown -R node:node . &&
             npm install -g pnpm@latest &&
             su node -c 'cd /app &&
             pnpm install --no-workspace-root --frozen-lockfile &&
             cd /app/shared &&
             pnpm install --frozen-lockfile &&
             pnpm build &&
             cd /app/server &&
             pnpm install --frozen-lockfile &&
             pnpm dev'"
    depends_on:
      - redis
      - mongodb

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mongodb:
    image: mongo:6-jammy
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  redis_data:
  mongodb_data:
  game_data:
  pnpm_store:
  client_modules:
  server_modules:
  shared_modules:
