services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
      - PORT=3000
      - REDIS_URL=redis://redis:6379
      - REDIS_PREFIX=ctorgame:dev
      - MONGODB_URL=mongodb://mongodb:27017
      - STORAGE_PATH=/app/data/games
      - REDIS_PASSWORD=
      - VITE_API_URL=http://localhost:3000
      - VITE_HOST=0.0.0.0
    depends_on:
      - mongodb
      - redis

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - 5173:5173
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:3000
      - VITE_HOST=0.0.0.0
    depends_on:
      - server

volumes:
  mongodb_data:
  redis_data: