version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.simple
    volumes:
      - .:/app
      - /app/node_modules
      - /app/shared/node_modules
      - /app/client/node_modules
      - /app/server/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    command: sh -c "cd /app && pnpm --filter @ctor-game/client dev"

  server:
    build:
      context: .
      dockerfile: Dockerfile.simple
    volumes:
      - .:/app
      - /app/node_modules
      - /app/shared/node_modules
      - /app/client/node_modules
      - /app/server/node_modules
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
      - MONGODB_URL=mongodb://mongodb:27017
    command: sh -c "cd /app && pnpm --filter @ctor-game/server dev"
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo:7.0.5
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:7.2.4
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
  redis_data: