FROM node:22-alpine

WORKDIR /app
#RUN npm install -g pnpm
RUN npm install -g pnpm@8.6.0

#nvm install 20
#npm install -g npm@10.9.1


COPY package.json pnpm-lock.yaml ./
RUN pnpm install

EXPOSE 3000
CMD ["pnpm", "dev"]